export const KANGJENNOMFOERES = {
  KAN: "KAN",
  KAN_IKKE: "KAN_IKKE",
  TILRETTELEGGING: "TILRETTELEGGING",
};
export const TILRETTELEGGING = {
  PAA_ANNET_STED: "PAA_ANNET_STED",
  MED_MER_TID: "MED_MER_TID",
  MED_HJELP: "MED_HJELP",
};
