export enum DataTestId {
  LANDING_OPPFOLGINGSPLAN_TEASER = "oppfolgingsplanTeaser",
  ARBEIDSOPPGAVE_LEGG_TIL_NY_OPPGAVE_BUTTON = "leggTilNyArbeidsoppgaveButton",
  ARBEIDSOPPGAVE_BESKRIVELSE_TEXTAREA = "beskrivArbeidsoppgavenTextArea",
  ARBEIDSOPPGAVE_KAN_GJENNOMFOERES_RADIO = "oppgaveKanGjennomfoeresRadio",
  ARBEIDSOPPGAVE_KAN_GJENNOMFOERES_TILRETTELEGGING_RADIO = "oppgaveKanGjennomfoeresMedTilretteleggingRadio",
  ARBEIDSOPPGAVE_KAN_IKKE_GJENNOMFOERES_RADIO = "oppgaveKanIkkeGjennomfoeresRadio",
  ARBEIDSOPPGAVE_LAGRE_OPPGAVE_BUTTON = "lagreArbeidsoppgaveButton",
  TILTAK_LEGG_TIL_NYTT_TILTAK_BUTTON = "leggTilNyttTiltakButton",
  TILTAK_OVERSKRIFT_TEXTFIELD = "tiltakOverskriftTextField",
  TILTAK_BESKRIVELSE_TEXTAREA = "beskrivTiltakTextArea",
  TILTAK_STARTDATO = "startDatoPaaTiltak",
  TILTAK_SLUTTDATO = "sluttDatoPaaTiltak",
  TILTAK_LAGRE_BUTTON = "lagreTiltakButton",
  SEPLANEN_JEG_ER_FERDIG_BUTTON = "jegErFerdigButton",
  SEPLANEN_STARTDATO = "startDato",
  SEPLANEN_SLUTTDATO = "sluttDato",
  SEPLANEN_EVALUERES_INNEN = "evalueresInnen",
  SEPLANEN_ENIG_I_PLANEN_CHECKBOX = "jegErEnigIPlanenCheckbox",
  SEPLANEN_SEND_TIL_GODKJENNING_BUTTON = "sendTilGodkjenningButton",
  NAVIGATION_FORRIGE_STEG_BUTTON = "forrigeStegButton",
  NAVIGATION_NESTE_STEG_BUTTON = "nesteStegButton",
  NAVIGATION_FORTSETT_SENERE_BUTTON = "fortsettSenereButton",
}
