export const HENTER_DINE_SYKMELDINGER = "HENTER_DINE_SYKMELDINGER";
export const HENT_DINE_SYKMELDINGER_FEILET = "HENT_DINE_SYKMELDINGER_FEILET";
export const SET_DINE_SYKMELDINGER = "SET_DINE_SYKMELDINGER";
export const SET_SORTERING = "SET_SORTERING";
export const HENT_DINE_SYKMELDINGER_FORESPURT =
  "HENT_DINE_SYKMELDINGER_FORESPURT";

export const HENT_LEDERE_FORESPURT = "HENT_LEDERE_FORESPURT";
export const HENTER_LEDERE = "HENTER_LEDERE";
export const LEDERE_HENTET = "LEDERE_HENTET";
export const HENT_LEDERE_FEILET = "HENT_LEDERE_FEILET";
