apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: oppfolgingsplan-frontend
  namespace: team-esyfo
  labels:
    team: team-esyfo
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  port: 8080
  tokenx:
    enabled: true
  idporten:
    enabled: true
    sidecar:
      enabled: true
  liveness:
    path: syk/oppfolgingsplaner/api/isAlive
    initialDelay: 20
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: syk/oppfolgingsplaner/api/isReady
    initialDelay: 20
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: actuator/metrics
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  ingresses:
    - "https://ekstern.dev.nav.no/syk/oppfolgingsplaner"
  env:
    - name: NPM_CONFIG_CACHE
      value: /tmp
    - name: DECORATOR_ENV
      value: "dev"
    - name: SYFOOPPFOLGINGSPLANSERVICE_HOST
      value: https://syfooppfolgingsplanservice.dev-fss-pub.nais.io
    - name: SYFOOPPFOLGINGSPLANSERVICE_CLIENT_ID
      value: dev-fss:team-esyfo:syfooppfolgingsplanservice
    - name: SYKMELDINGER_ARBEIDSGIVER_HOST
      value: https://sykmeldinger-arbeidsgiver.dev.nav.no
    - name : SYKMELDINGER_ARBEIDSGIVER_CLIENT_ID
      value: "dev-gcp:teamsykmelding:sykmeldinger-arbeidsgiver"
    - name: MOCK_BACKEND
      value: "false"
    - name: RUNTIME_ENVIRONMENT
      value: dev
  accessPolicy:
    outbound:
      external:
        - host: dekoratoren.dev.nav.no
        - host: syfooppfolgingsplanservice.dev-fss-pub.nais.io
