apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{appname}}-demo
  namespace: team-esyfo
  labels:
    team: team-esyfo
    branchState: {{branchState}}
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  port: 3000
  tokenx:
    enabled: false
  idporten:
    enabled: false
    sidecar:
      enabled: false
  liveness:
    path: syk/oppfolgingsplaner/api/isAlive
    initialDelay: 20
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: syk/oppfolgingsplaner/api/isReady
    initialDelay: 20
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /actuator/metrics
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  ingresses:
    - {{ingress}}
  accessPolicy:
    outbound:
      external:
        - host: nav.no
        - host: dekoratoren.nav.no
  env:
    - name: NPM_CONFIG_CACHE
      value: /tmp
    - name: DECORATOR_ENV
      value: "prod"
    - name: SYFOOPPFOLGINGSPLANSERVICE_HOST
      value: https://syfooppfolgingsplanservice.dev-fss-pub.nais.io
    - name: SYFOOPPFOLGINGSPLANSERVICE_CLIENT_ID
      value: syfooppfolgingsplanservice
    - name: MOCK_BACKEND
      value: "true"
    - name: RUNTIME_ENVIRONMENT
      value: demo
