apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: oppfolgingsplaner-frontend
  namespace: team-esyfo
  labels:
    team: team-esyfo
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /isAlive
    initialDelay: 20
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /isReady
    initialDelay: 20
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /actuator/metrics
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  ingresses:
    - "https://oppfolgingsplaner.labs.nais.io/"
  env:
    - name: DECORATOR_URL
      value: https://dekoratoren.dev.nav.no
    - name: DECORATOR_ENV
      value: "prod"
    - name: LOGINSERVICE_URL
      value: https://loginservice.dev.nav.no/login
    - name: DITTNAV_URL
      value: https://www.nav.no/person/dittnav
    - name: SYFOOPPFOLGINGSPLANSERVICE_HOST
      value: https://syfooppfolgingsplanservice.dev-fss-pub.nais.io
    - name: DINE_SYKMELDTE_ROOT
      value: https://www.nav.no/arbeidsgiver/sykmeldte
    - name: DITT_SYKEFRAVAER_ROOT
      value: https://www.nav.no/syk/sykefravaer
