name: label-dependabot-pr
on:
  pull_request_target:
    types:
      - opened
      - unlabeled

jobs:
  next-app:
    uses: navikt/teamesyfo-github-actions-workflows/.github/workflows/label-dependabot-pr.yaml@main
    secrets: inherit
