name: label-dependabot-pr
on:
  pull_request:
    types:
      - opened
      - unlabeled

jobs:
  label-dependabot-pr:
    name: Add team as reviewers on major updates
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Add Reviewers
        uses: madrapps/add-reviewers@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          reviewers: team-esyfo
          re-request-when-changes-requested: true
          re-request-when-approved: true
          debug-mode: true
