name: label-dependabot-pr
on:
  pull_request:
    types:
      - opened
      - unlabeled

jobs:
  label-dependabot-pr:
    name: Add team as reviewers on major updates
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Tagg
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          debug: true
          script: |
            github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              team_reviewers: ["team-halloisen"]
            });
