name: Upload rarely changed public files to NAV CDN
on:
  push:
    paths:
      - public/**

jobs:
  build:
    name: upload public files to NAV CDN
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v5
      - name: Upload public files to NAV CDN
        uses: nais/deploy/actions/cdn-upload/v2@master
        with:
          team: team-esyfo
          source: ./public
          destination: '/oppfolgingsplan-frontend'
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
